import type { AiHelpResult, CommentMode, DuplicateCandidate, SimilarIssueCandidate } from "../core/types.js";

const zhAiNote = "> 注：以上内容由 AI 生成，仅供参考，请结合项目文档、代码和维护者意见进一步确认。";
const enAiNote = "> Note: This response was generated by AI for reference only. Please verify it against the project docs, code, and maintainer guidance.";

type AiCommentLayout = {
  titleZh: string;
  titleEn: string;
  summaryZh: string;
  summaryEn: string;
  analysisZh: string;
  analysisEn: string;
  actionZh: string;
  actionEn: string;
  missingZh: string;
  missingEn: string;
};

function bilingual(mode: CommentMode, zh: string, en: string): string {
  if (mode === "zh") {
    return zh;
  }

  return `${zh}\n\n---\n\n${en}`;
}

function renderList(items: string[], emptyLabel: string): string[] {
  if (items.length === 0) {
    return [`- ${emptyLabel}`];
  }

  return items.map((item) => `- ${item}`);
}

function renderIssueState(mode: "zh" | "en", state: "open" | "closed"): string {
  if (mode === "zh") {
    return state === "open" ? "开放" : "已关闭";
  }

  return state;
}

function getAiCommentLayout(templateKey?: string): AiCommentLayout {
  switch (templateKey) {
    case "bug":
      return {
        titleZh: "AI 分析建议",
        titleEn: "AI Guidance",
        summaryZh: "问题概述",
        summaryEn: "Summary",
        analysisZh: "可能原因",
        analysisEn: "Possible Causes",
        actionZh: "建议排查步骤",
        actionEn: "Suggested Troubleshooting Steps",
        missingZh: "仍需补充的信息",
        missingEn: "Additional Information Needed"
      };
    case "question":
      return {
        titleZh: "AI 参考回答",
        titleEn: "AI Reference Answer",
        summaryZh: "直接回答",
        summaryEn: "Direct Answer",
        analysisZh: "判断依据",
        analysisEn: "Key Points",
        actionZh: "建议下一步",
        actionEn: "Suggested Next Steps",
        missingZh: "如需进一步确认",
        missingEn: "If More Context Is Needed"
      };
    case "feature":
    case "suggestion":
      return {
        titleZh: "AI 方案建议",
        titleEn: "AI Proposal Suggestions",
        summaryZh: "需求理解",
        summaryEn: "Request Summary",
        analysisZh: "可行思路",
        analysisEn: "Feasible Approaches",
        actionZh: "建议实施路径",
        actionEn: "Suggested Implementation Path",
        missingZh: "仍需确认的信息",
        missingEn: "Information To Confirm"
      };
    default:
      return {
        titleZh: "AI 参考建议",
        titleEn: "AI Reference Suggestions",
        summaryZh: "问题理解",
        summaryEn: "Issue Understanding",
        analysisZh: "分析要点",
        analysisEn: "Key Analysis",
        actionZh: "建议处理方向",
        actionEn: "Suggested Next Actions",
        missingZh: "仍需补充的信息",
        missingEn: "Additional Information Needed"
      };
  }
}

export function renderValidationComment(params: {
  mode: CommentMode;
  valid: boolean;
  templateKey?: string;
  missingSections: string[];
}): string {
  if (params.valid) {
    return bilingual(
      params.mode,
      `## 模板检查结果\n\n已通过模板检查。当前识别模板：\`${params.templateKey ?? "unknown"}\`。`,
      `## Template Check Result\n\nThe issue passed template validation. Detected template: \`${params.templateKey ?? "unknown"}\`.`
    );
  }

  const zhMissing = params.missingSections.map((item) => `- ${item}`).join("\n") || "- 暂无";
  const enMissing = params.missingSections.map((item) => `- ${item}`).join("\n") || "- None";

  return bilingual(
    params.mode,
    `## 模板检查结果\n\nIssue 未通过模板检查，请补充以下必填内容：\n${zhMissing}`,
    `## Template Check Result\n\nThis issue did not pass template validation. Please complete the following required sections:\n${enMissing}`
  );
}

export function renderDuplicateComment(params: {
  mode: CommentMode;
  duplicateOf: DuplicateCandidate;
  confidence: number;
}): string {
  const issueRef = `#${params.duplicateOf.number}`;
  const zh = [
    issueRef,
    "",
    "## 重复 Issue 处理",
    "",
    `当前 Issue 已被判定为与 #${params.duplicateOf.number} 重复，已自动关闭。`,
    "",
    `- 置信度：${params.confidence.toFixed(2)}`
  ].join("\n");
  const en = [
    issueRef,
    "",
    "## Duplicate Issue Handling",
    "",
    `This issue was identified as a duplicate of #${params.duplicateOf.number} and has been closed automatically.`,
    "",
    `- Confidence: ${params.confidence.toFixed(2)}`
  ].join("\n");

  return params.mode === "zh" ? zh : `${zh}\n\n---\n\n${en}`;
}

export function renderSimilarIssuesComment(params: {
  mode: CommentMode;
  issues: SimilarIssueCandidate[];
}): string {
  const issueRefs = params.issues.map((entry) => `#${entry.candidate.number}`).join(" ");
  const zhLines = params.issues.map((entry, index) =>
    `${index + 1}. #${entry.candidate.number} ${entry.candidate.title} | 状态：${renderIssueState("zh", entry.candidate.state)} | 相似度：${entry.score.toFixed(2)}`
  );
  const enLines = params.issues.map((entry, index) =>
    `${index + 1}. #${entry.candidate.number} ${entry.candidate.title} | State: ${renderIssueState("en", entry.candidate.state)} | Score: ${entry.score.toFixed(2)}`
  );

  const zh = [
    issueRefs,
    "",
    "## 可能相关的历史 Issue",
    "",
    "当前 Issue 未被自动判定为重复，但检测到以下相似 Issue。提交前或继续排查前，建议先确认是否已经有人反馈过同类问题。",
    "",
    "<details>",
    `<summary>展开查看 ${params.issues.length} 个相关 Issue</summary>`,
    "",
    ...zhLines,
    "",
    "</details>"
  ].join("\n");

  if (params.mode === "zh") {
    return zh;
  }

  const en = [
    issueRefs,
    "",
    "## Possibly Related Issues",
    "",
    "This issue was not auto-closed as a duplicate, but the following similar issues were detected. Check them first before continuing triage.",
    "",
    "<details>",
    `<summary>Expand to view ${params.issues.length} related issues</summary>`,
    "",
    ...enLines,
    "",
    "</details>"
  ].join("\n");

  return `${zh}\n\n---\n\n${en}`;
}

export function renderAiHelpComment(params: {
  mode: CommentMode;
  templateKey?: string;
  help: AiHelpResult;
}): string {
  const layout = getAiCommentLayout(params.templateKey);
  const zh = [
    `## ${layout.titleZh}`,
    "",
    `### ${layout.summaryZh}\n${params.help.summary}`,
    "",
    `### ${layout.analysisZh}`,
    ...renderList(params.help.possibleCauses, "暂无"),
    "",
    `### ${layout.actionZh}`,
    ...renderList(params.help.troubleshootingSteps, "暂无"),
    "",
    `### ${layout.missingZh}`,
    ...renderList(params.help.missingInformation, "暂无"),
    "",
    zhAiNote
  ].join("\n");

  if (params.mode === "zh") {
    return zh;
  }

  const en = [
    `## ${layout.titleEn}`,
    "",
    `### ${layout.summaryEn}\n${params.help.summary}`,
    "",
    `### ${layout.analysisEn}`,
    ...renderList(params.help.possibleCauses, "None"),
    "",
    `### ${layout.actionEn}`,
    ...renderList(params.help.troubleshootingSteps, "None"),
    "",
    `### ${layout.missingEn}`,
    ...renderList(params.help.missingInformation, "None"),
    "",
    enAiNote
  ].join("\n");

  return `${zh}\n\n---\n\n${en}`;
}
