import { describe, expect, it } from "vitest";

import { renderAiHelpComment } from "../../src/i18n/comments.js";

const help = {
  summary: "Example summary.",
  possibleCauses: ["Example cause"],
  troubleshootingSteps: ["Example step"],
  missingInformation: ["Example missing info"]
};

describe("renderAiHelpComment", () => {
  it("uses note-style AI hint instead of disclaimer wording", () => {
    const comment = renderAiHelpComment({
      mode: "zh",
      templateKey: "bug",
      help
    });

    expect(comment).toContain("> 注：以上内容由 AI 生成，仅供参考");
    expect(comment).not.toContain("免责声明");
  });

  it("renders question issues with a question-oriented layout in bilingual mode", () => {
    const comment = renderAiHelpComment({
      mode: "zh-en",
      templateKey: "question",
      help
    });

    expect(comment).toContain("## AI 参考回答");
    expect(comment).toContain("### 直接回答");
    expect(comment).toContain("### 判断依据");
    expect(comment).toContain("### 建议下一步");
    expect(comment).toContain("## AI Reference Answer");
    expect(comment).toContain("### Direct Answer");
    expect(comment).toContain("### Key Points");
    expect(comment).toContain("> Note: This response was generated by AI for reference only.");
    expect(comment).not.toContain("### 可能原因");
    expect(comment).not.toContain("### 建议排查步骤");
  });
});
