import { describe, expect, it } from "vitest";

import { renderAiHelpComment } from "../../src/i18n/comments.js";

const help = {
  summary: "Example summary.",
  possibleCauses: ["Example cause"],
  troubleshootingSteps: ["Example step"],
  missingInformation: ["Example missing info"]
};

describe("renderAiHelpComment", () => {
  it("appends a disclaimer in Chinese mode", () => {
    const comment = renderAiHelpComment({
      mode: "zh",
      help
    });

    expect(comment).toContain("免责声明：以上回复内容由 AI 生成，仅供参考");
  });

  it("appends disclaimers in both languages for bilingual mode", () => {
    const comment = renderAiHelpComment({
      mode: "zh-en",
      help
    });

    expect(comment).toContain("免责声明：以上回复内容由 AI 生成，仅供参考");
    expect(comment).toContain("Disclaimer: This response was generated by AI for reference only.");
  });
});
