import { describe, expect, it } from "vitest";

import {
  renderAiHelpComment,
  renderFixStatusComment,
  renderFixSuggestionComment,
  renderSimilarIssuesComment
} from "../../src/i18n/comments.js";

const help = {
  summary: "Example summary.",
  possibleCauses: ["Example cause"],
  troubleshootingSteps: ["Example step"],
  missingInformation: ["Example missing info"]
};

describe("comment renderers", () => {
  it("uses note-style AI hint instead of disclaimer wording", () => {
    const comment = renderAiHelpComment({
      mode: "zh",
      templateKey: "bug",
      help
    });

    expect(comment).toContain("> 注：以上内容由 AI 生成，仅供参考");
    expect(comment).not.toContain("免责声明");
  });

  it("renders question issues with a question-oriented layout in bilingual mode", () => {
    const comment = renderAiHelpComment({
      mode: "zh-en",
      templateKey: "question",
      help
    });

    expect(comment).toContain("## AI 参考回答");
    expect(comment).toContain("### 直接回答");
    expect(comment).toContain("### 判断依据");
    expect(comment).toContain("### 建议下一步");
    expect(comment).toContain("## AI Reference Answer");
    expect(comment).toContain("### Direct Answer");
    expect(comment).toContain("### Key Points");
    expect(comment).toContain("> Note: This response was generated by AI for reference only.");
    expect(comment).not.toContain("### 可能原因");
    expect(comment).not.toContain("### 建议排查步骤");
  });

  it("renders related issues at the top of the AI comment", () => {
    const comment = renderAiHelpComment({
      mode: "zh",
      templateKey: "bug",
      help,
      relatedIssues: [
        {
          candidate: {
            number: 16,
            title: "[bug] 一条龙设置无法保存",
            body: "",
            labels: ["bug"],
            state: "open",
            htmlUrl: "https://example.test/issues/16",
            createdAt: "2026-01-01T00:00:00Z",
            updatedAt: "2026-01-01T00:00:00Z"
          },
          score: 0.33
        }
      ]
    });

    expect(comment.startsWith("## 可能相关的历史 Issue")).toBe(true);
    expect(comment).toContain("<details>");
    expect(comment).toContain("#16 | 相似度：0.33");
    expect(comment).toContain("## AI 分析建议");
  });

  it("renders similar issues inside a collapsible block", () => {
    const comment = renderSimilarIssuesComment({
      mode: "zh-en",
      issues: [
        {
          candidate: {
            number: 16,
            title: "[bug] 一条龙设置无法保存",
            body: "",
            labels: ["bug"],
            state: "open",
            htmlUrl: "https://example.test/issues/16",
            createdAt: "2026-01-01T00:00:00Z",
            updatedAt: "2026-01-01T00:00:00Z"
          },
          score: 0.33
        }
      ]
    });

    expect(comment).toContain("## 可能相关的历史 Issue");
    expect(comment).toContain("#16 | 相似度：0.33");
    expect(comment).toContain("<details>");
    expect(comment).toContain("展开查看 1 个相关 Issue");
    expect(comment).toContain("## Possibly Related Issues");
    expect(comment).toContain("#16 | Score：0.33");
    expect(comment).toContain("Expand to view 1 related issues");
  });

  it("renders fix suggestions with patch draft and candidate files", () => {
    const comment = renderFixSuggestionComment({
      mode: "zh",
      suggestion: {
        summary: "需要调整配置保存逻辑。",
        candidateFiles: [
          {
            path: "src/config/save.ts",
            reason: "保存逻辑集中在这里。"
          }
        ],
        changeSuggestions: ["统一处理 index 字段的旧格式。"],
        patchDraft: "@@\n- old\n+ new",
        verificationSteps: ["使用旧配置文件启动后再次保存。"],
        risks: ["可能影响旧版本配置兼容。"]
      }
    });

    expect(comment).toContain("## AI 修复建议");
    expect(comment).toContain("`src/config/save.ts`：保存逻辑集中在这里。");
    expect(comment).toContain("```diff");
    expect(comment).toContain("> 注：以上内容由 AI 生成，仅供参考");
  });

  it("renders fix status comments without disclaimer wording", () => {
    const comment = renderFixStatusComment({
      mode: "zh-en",
      titleZh: "AI 修复建议",
      titleEn: "AI Fix Suggestion",
      messageZh: "当前 Issue 已关闭。",
      messageEn: "This issue is already closed."
    });

    expect(comment).toContain("## AI 修复建议");
    expect(comment).toContain("## AI Fix Suggestion");
    expect(comment).not.toContain("免责声明");
    expect(comment).not.toContain("> 注：以上内容由 AI 生成，仅供参考");
  });
});
